"""Build the standalone HTML file conhecimento-akitando.html.

Reads workspace_payload.json (generated by build_payload.py) and writes a
single-file HTML with embedded CSS, JS and the data as a JSON literal.
"""
import json, html

payload = json.load(open('workspace_payload.json'))
videos = payload['videos']
pilar_order = payload['pilar_order']
pilar_count = payload['pilar_count']
prio_count = payload['prio_count']
DESC = payload['desc']
total = payload['total']
total_pilares = payload['total_pilares']

# Group by pilar preserving pilar_order
from collections import defaultdict
by_pilar = defaultdict(list)
for v in videos: by_pilar[v['pilar']].append(v)

# Pre-compute per-pilar "conceitos-chave agregados" - just titles + first few concepts per video
# to give a glance of the pilar's main themes
def esc(s):
    return html.escape(s, quote=True).replace('"', '&quot;').replace("'", '&#39;')

# Build JSON literal for embedding in <script>
embed = json.dumps(payload, ensure_ascii=False, separators=(',', ':'))

# Build pillar sections HTML
def render_video_card(v):
    prio_cls = {'Alta':'prio-alta','Média':'prio-med','Baixa':'prio-bai'}.get(v['prioridade'],'prio-bai')
    concepts = v['conceitos']
    # Limit concept preview to ~6 items to keep cards compact
    concept_items = []
    for c in [x.strip() for x in concepts.split(';') if x.strip()]:
        concept_items.append(f'<span class="concept">{esc(c)}</span>')
    sec_html = ''
    if v['pilaresSecundarios']:
        sec_html = '<div class="sec">também: ' + ', '.join(esc(s) for s in v['pilaresSecundarios']) + '</div>'
    return (
        f'<article class="card" data-pilar="{esc(v["pilar"])}" data-prio="{esc(v["prioridade"])}" data-search="{(esc(v["title"]+" "+v["conceitos"]+" "+v["sintese"]+" "+v["pilar"]+" "+" ".join(v["pilaresSecundarios"])).lower())}">'
        f'<div class="card-head">'
        f'<a class="card-title" href="{esc(v["url"])}" target="_blank" rel="noopener">{esc(v["title"])}</a>'
        f'<span class="prio {prio_cls}">{esc(v["prioridade"])}</span>'
        f'</div>'
        f'<div class="card-meta"><span class="dur">⏱ {esc(v["duracao"])}</span>{sec_html}</div>'
        f'<p class="sintese">{esc(v["sintese"])}</p>'
        f'<div class="concepts">{"".join(concept_items)}</div>'
        f'</article>'
    )

pilar_sections = []
for p in pilar_order:
    desc = DESC.get(p, '')
    pcount = pilar_count[p]
    cards = '\n'.join(render_video_card(v) for v in by_pilar[p])
    pid = 'p-' + p.split('.')[0].strip()
    pilar_sections.append(f'''
<section class="pilar" id="{pid}" data-pilar="{esc(p)}" data-count="{pcount}">
  <header class="pilar-head">
    <h2>{esc(p)}</h2>
    <span class="badge-count">{pcount} {'vídeo' if pcount==1 else 'vídeos'}</span>
  </header>
  <p class="pilar-desc">{esc(desc)}</p>
  <div class="cards">{cards}</div>
</section>
''')

pilar_nav = '\n'.join(
    f'<li><a href="#p-{p.split(".")[0].strip()}"><span class="dot"></span>{esc(p)} <em>{pilar_count[p]}</em></a></li>'
    for p in pilar_order
)

# Overview
html_doc = f'''<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Conhecimento Akitando — Pilares de Conhecimento do Canal</title>
<style>
  :root {{
    --bg: #0f1115;
    --bg-2: #161a22;
    --bg-3: #1d2330;
    --fg: #e6e9ef;
    --fg-dim: #9aa3b2;
    --fg-mute: #6b7484;
    --line: #232a36;
    --accent: #6cb6ff;
    --accent-2: #b58cff;
    --alta: #2bd9a3;
    --alta-bg: rgba(43,217,163,0.12);
    --alta-bd: rgba(43,217,163,0.35);
    --med: #f0b656;
    --med-bg: rgba(240,182,86,0.13);
    --med-bd: rgba(240,182,86,0.35);
    --bai: #e26b6b;
    --bai-bg: rgba(226,107,107,0.13);
    --bai-bd: rgba(226,107,107,0.35);
    --shadow: 0 4px 20px rgba(0,0,0,0.35);
    --radius: 12px;
  }}
  * {{ box-sizing: border-box; }}
  html, body {{ margin: 0; padding: 0; background: var(--bg); color: var(--fg); font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; line-height: 1.55; }}
  a {{ color: var(--accent); text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  code {{ background: var(--bg-3); padding: 1px 5px; border-radius: 4px; font-size: 0.92em; }}

  /* Layout */
  .wrap {{ max-width: 1200px; margin: 0 auto; padding: 0 20px; }}
  header.hero {{
    background: linear-gradient(135deg, #1a1f2c 0%, #15171f 100%);
    border-bottom: 1px solid var(--line);
    padding: 36px 0 28px;
  }}
  header.hero h1 {{ margin: 0 0 6px; font-size: 28px; letter-spacing: -0.01em; }}
  header.hero .sub {{ color: var(--fg-dim); margin: 0 0 14px; font-size: 15px; }}
  header.hero .sub a {{ color: var(--accent); }}

  .overview {{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
    gap: 14px;
    margin-top: 18px;
  }}
  .stat {{
    background: var(--bg-2);
    border: 1px solid var(--line);
    border-radius: var(--radius);
    padding: 14px 16px;
  }}
  .stat .num {{ font-size: 26px; font-weight: 700; color: var(--fg); }}
  .stat .lbl {{ font-size: 12px; color: var(--fg-dim); text-transform: uppercase; letter-spacing: 0.04em; margin-top: 2px; }}
  .stat.alta .num {{ color: var(--alta); }}
  .stat.med  .num {{ color: var(--med); }}
  .stat.bai  .num {{ color: var(--bai); }}

  .legend {{ display: flex; gap: 10px; flex-wrap: wrap; margin-top: 12px; font-size: 13px; color: var(--fg-dim); }}
  .legend .item {{ display: inline-flex; align-items: center; gap: 6px; }}
  .legend .swatch {{ width: 10px; height: 10px; border-radius: 2px; display: inline-block; }}

  /* Controls */
  .controls {{
    position: sticky;
    top: 0;
    z-index: 10;
    background: rgba(15,17,21,0.95);
    backdrop-filter: blur(8px);
    border-bottom: 1px solid var(--line);
    padding: 14px 0;
  }}
  .controls .row {{ display: grid; grid-template-columns: 1fr auto auto auto auto; gap: 10px; align-items: center; }}
  .controls input[type="search"], .controls select {{
    background: var(--bg-2);
    border: 1px solid var(--line);
    color: var(--fg);
    padding: 8px 12px;
    border-radius: 8px;
    font-size: 14px;
    font-family: inherit;
  }}
  .controls input[type="search"] {{ width: 100%; }}
  .controls input[type="search"]:focus, .controls select:focus {{ outline: none; border-color: var(--accent); }}
  .controls select {{ cursor: pointer; min-width: 110px; }}
  .controls .summary {{ grid-column: 1 / -1; font-size: 13px; color: var(--fg-dim); margin-top: 4px; }}
  .controls .summary strong {{ color: var(--fg); }}
  .clear-btn {{ background: var(--bg-3); color: var(--fg-dim); border: 1px solid var(--line); padding: 8px 12px; border-radius: 8px; cursor: pointer; font-size: 13px; font-family: inherit; }}
  .clear-btn:hover {{ color: var(--fg); border-color: var(--accent); }}

  /* Pilares */
  .layout {{ display: grid; grid-template-columns: 240px 1fr; gap: 30px; margin-top: 20px; }}
  @media (max-width: 880px) {{ .layout {{ grid-template-columns: 1fr; }} .pilar-nav {{ position: static !important; }} }}
  .pilar-nav {{
    position: sticky; top: 80px; align-self: start;
    background: var(--bg-2); border: 1px solid var(--line); border-radius: var(--radius);
    padding: 14px; max-height: calc(100vh - 100px); overflow-y: auto;
  }}
  .pilar-nav h3 {{ margin: 0 0 8px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: var(--fg-mute); }}
  .pilar-nav ul {{ list-style: none; padding: 0; margin: 0; }}
  .pilar-nav li a {{ display: flex; align-items: center; gap: 8px; padding: 6px 8px; border-radius: 6px; color: var(--fg-dim); font-size: 13px; }}
  .pilar-nav li a:hover {{ background: var(--bg-3); color: var(--fg); text-decoration: none; }}
  .pilar-nav li a em {{ color: var(--fg-mute); font-style: normal; font-size: 12px; margin-left: auto; }}
  .pilar-nav .dot {{ width: 8px; height: 8px; border-radius: 50%; background: var(--accent); flex-shrink: 0; }}

  .pilar {{
    background: var(--bg-2);
    border: 1px solid var(--line);
    border-radius: var(--radius);
    margin-bottom: 22px;
    overflow: hidden;
  }}
  .pilar-head {{ display: flex; align-items: center; gap: 12px; padding: 18px 20px 8px; }}
  .pilar-head h2 {{ margin: 0; font-size: 19px; color: var(--fg); }}
  .badge-count {{ background: var(--bg-3); color: var(--fg-dim); padding: 2px 8px; border-radius: 999px; font-size: 12px; }}
  .pilar-desc {{ color: var(--fg-dim); font-size: 14px; margin: 4px 20px 16px; }}

  .cards {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 12px; padding: 0 20px 20px; }}
  .card {{
    background: var(--bg-3);
    border: 1px solid var(--line);
    border-radius: 10px;
    padding: 14px;
    display: flex; flex-direction: column; gap: 8px;
  }}
  .card:hover {{ border-color: var(--accent); transform: translateY(-1px); transition: 0.15s; }}
  .card-head {{ display: flex; gap: 8px; align-items: flex-start; justify-content: space-between; }}
  .card-title {{ font-weight: 600; color: var(--fg); font-size: 14px; line-height: 1.35; flex: 1; }}
  .card-title:hover {{ color: var(--accent); }}
  .prio {{ font-size: 11px; padding: 2px 8px; border-radius: 4px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em; flex-shrink: 0; }}
  .prio-alta {{ background: var(--alta-bg); color: var(--alta); border: 1px solid var(--alta-bd); }}
  .prio-med  {{ background: var(--med-bg);  color: var(--med);  border: 1px solid var(--med-bd); }}
  .prio-bai  {{ background: var(--bai-bg);  color: var(--bai);  border: 1px solid var(--bai-bd); }}
  .card-meta {{ display: flex; gap: 8px; align-items: center; font-size: 12px; color: var(--fg-mute); flex-wrap: wrap; }}
  .card-meta .sec {{ color: var(--fg-mute); font-size: 11px; font-style: italic; }}
  .dur {{ color: var(--fg-dim); }}
  .sintese {{ margin: 0; font-size: 13px; color: var(--fg-dim); line-height: 1.5; }}
  .concepts {{ display: flex; flex-wrap: wrap; gap: 4px; margin-top: 2px; }}
  .concept {{ background: var(--bg-2); color: var(--fg-dim); padding: 2px 7px; border-radius: 4px; font-size: 11px; border: 1px solid var(--line); }}

  .empty {{ text-align: center; padding: 60px 20px; color: var(--fg-dim); display: none; }}
  .empty.show {{ display: block; }}
  .empty h3 {{ color: var(--fg); margin: 0 0 8px; }}

  .pilar.hidden, .card.hidden {{ display: none; }}
  footer {{ text-align: center; padding: 30px 20px; color: var(--fg-mute); font-size: 12px; }}
</style>
</head>
<body>

<header class="hero">
  <div class="wrap">
    <h1>Conhecimento Akitando</h1>
    <p class="sub">Mapa de <strong>{total} vídeos</strong> do canal <a href="https://www.youtube.com/@Akitando" target="_blank" rel="noopener">@Akitando</a> (Fabio Akita), agrupados em <strong>{total_pilares} pilares de conhecimento</strong> e classificados por prioridade (o que é atemporal vs. efêmero).</p>
    <div class="overview">
      <div class="stat"><div class="num">{total}</div><div class="lbl">vídeos no acervo</div></div>
      <div class="stat"><div class="num">{total_pilares}</div><div class="lbl">pilares de conhecimento</div></div>
      <div class="stat alta"><div class="num">{prio_count.get("Alta",0)}</div><div class="lbl">Alta (atemporal)</div></div>
      <div class="stat med"><div class="num">{prio_count.get("Média",0)}</div><div class="lbl">Média (aplicado)</div></div>
      <div class="stat bai"><div class="num">{prio_count.get("Baixa",0)}</div><div class="lbl">Baixa (opinião/datado)</div></div>
    </div>
    <div class="legend">
      <span class="item"><span class="swatch" style="background:var(--alta)"></span> <strong>Alta</strong> = atemporal/fundacional — não envelhece</span>
      <span class="item"><span class="swatch" style="background:var(--med)"></span> <strong>Média</strong> = aplicado/intermediário — útil mas mais datado</span>
      <span class="item"><span class="swatch" style="background:var(--bai)"></span> <strong>Baixa</strong> = opinião/conjuntura/biografia — datado ou pessoal</span>
    </div>
  </div>
</header>

<div class="controls">
  <div class="wrap">
    <div class="row">
      <input type="search" id="q" placeholder="🔍  Buscar por título, conceito, pilar…" autocomplete="off">
      <select id="fPilar" aria-label="Filtrar por pilar">
        <option value="">Todos os pilares</option>
      </select>
      <select id="fPrio" aria-label="Filtrar por prioridade">
        <option value="">Todas as prioridades</option>
        <option value="Alta">Apenas Alta</option>
        <option value="Média">Apenas Média</option>
        <option value="Baixa">Apenas Baixa</option>
      </select>
      <select id="fSort" aria-label="Ordenar">
        <option value="default">Ordem padrão</option>
        <option value="prio-asc">Prioridade: Alta → Baixa</option>
        <option value="prio-desc">Prioridade: Baixa → Alta</option>
        <option value="title-asc">Título A→Z</option>
        <option value="title-desc">Título Z→A</option>
      </select>
      <button class="clear-btn" id="clear" title="Limpar filtros">✕ Limpar</button>
      <div class="summary" id="summary"></div>
    </div>
  </div>
</div>

<main class="wrap">
  <div class="layout">
    <aside class="pilar-nav">
      <h3>Pilares ({total_pilares})</h3>
      <ul>{pilar_nav}</ul>
    </aside>
    <div id="content">
      {''.join(pilar_sections)}
      <div class="empty" id="empty">
        <h3>Nada encontrado</h3>
        <p>Tente outra busca ou remova os filtros.</p>
      </div>
    </div>
  </div>
</main>

<footer>
  Gerado automaticamente a partir das transcrições do canal @Akitando.
  Sem dependências externas — abre offline no browser.
</footer>

<script>
const PAYLOAD = {embed};
const VIDEOS = PAYLOAD.videos;
const PILAR_ORDER = PAYLOAD.pilar_order;
const PILAR_DESC = PAYLOAD.desc;
const PRIO_RANK = {{Alta:0, "Média":1, Baixa:2}};

const $ = (s) => document.querySelector(s);
const $$ = (s) => Array.from(document.querySelectorAll(s));

// Populate pilar select
const fPilar = $('#fPilar');
PILAR_ORDER.forEach(p => {{
  const o = document.createElement('option');
  o.value = p; o.textContent = p;
  fPilar.appendChild(o);
}});

const qEl = $('#q');
const fPrioEl = $('#fPrio');
const fSortEl = $('#fSort');
const summaryEl = $('#summary');
const emptyEl = $('#empty');

function applyFilters() {{
  const q = qEl.value.trim().toLowerCase();
  const p = fPilar.value;
  const pr = fPrioEl.value;
  const sort = fSortEl.value;
  let total = 0;
  const byPilar = {{}};

  $$('.pilar').forEach(section => {{
    const pilar = section.dataset.pilar;
    if (p && pilar !== p) {{ section.classList.add('hidden'); return; }}
    let cards = Array.from(section.querySelectorAll('.card'));
    cards.forEach(c => {{
      const matchesPrio = !pr || c.dataset.prio === pr;
      const matchesQ = !q || c.dataset.search.includes(q);
      if (matchesPrio && matchesQ) c.classList.remove('hidden'); else c.classList.add('hidden');
    }});
    const visible = cards.filter(c => !c.classList.contains('hidden'));
    if (visible.length === 0) section.classList.add('hidden'); else section.classList.remove('hidden');
    byPilar[pilar] = visible.length;
    total += visible.length;
  }});

  // sort cards within each section
  $$('.pilar').forEach(section => {{
    const cards = Array.from(section.querySelectorAll('.card'));
    const data = cards.map(c => VIDEOS.find(v => v.videoId === c.querySelector('.card-title').href.split('v=')[1]));
    let cmp;
    if (sort === 'prio-asc' || sort === 'prio-desc') {{
      const dir = sort === 'prio-asc' ? 1 : -1;
      cmp = (a, b) => (PRIO_RANK[a.dataset.prio] - PRIO_RANK[b.dataset.prio]) * dir;
    }} else if (sort === 'title-asc' || sort === 'title-desc') {{
      const dir = sort === 'title-asc' ? 1 : -1;
      cmp = (a, b) => a.querySelector('.card-title').textContent.localeCompare(b.querySelector('.card-title').textContent) * dir;
    }} else {{
      // default: keep insertion order (already sorted Alta->Baixa by build)
      return;
    }}
    cards.sort(cmp);
    const container = section.querySelector('.cards');
    cards.forEach(c => container.appendChild(c));
  }});

  // update pilar nav counts
  $$('.pilar-nav li a').forEach(a => {{
    const href = a.getAttribute('href');
    const sec = document.querySelector(href);
    if (!sec) return;
    const n = byPilar[sec.dataset.pilar] || 0;
    const em = a.querySelector('em'); if (em) em.textContent = n;
  }});

  // Summary
  if (total === 0) {{
    emptyEl.classList.add('show');
    summaryEl.innerHTML = '<strong>0</strong> vídeos visíveis';
  }} else {{
    emptyEl.classList.remove('show');
    const filters = [];
    if (q) filters.push(`busca: <em>"${{q.replace(/</g,'&lt;')}}"</em>`);
    if (p) filters.push(`pilar: <em>${{p}}</em>`);
    if (pr) filters.push(`prioridade: <em>${{pr}}</em>`);
    const filtTxt = filters.length ? ' &middot; ' + filters.join(' &middot; ') : '';
    summaryEl.innerHTML = `<strong>${{total}}</strong> de {total} vídeos visíveis$filtTxt`;
  }}
}}

qEl.addEventListener('input', applyFilters);
fPilar.addEventListener('change', applyFilters);
fPrioEl.addEventListener('change', applyFilters);
fSortEl.addEventListener('change', applyFilters);
$('#clear').addEventListener('click', () => {{
  qEl.value = ''; fPilar.value = ''; fPrioEl.value = ''; fSortEl.value = 'default';
  applyFilters();
  qEl.focus();
}});

// Smooth scroll for nav links
$$('.pilar-nav a').forEach(a => {{
  a.addEventListener('click', e => {{
    e.preventDefault();
    const t = document.querySelector(a.getAttribute('href'));
    if (t) {{ t.scrollIntoView({{behavior:'smooth', block:'start'}}); }}
  }});
}});

applyFilters();
</script>
</body>
</html>
'''

open('conhecimento-akitando.html', 'w', encoding='utf-8').write(html_doc)
print('wrote conhecimento-akitando.html', len(html_doc), 'bytes')
